# Generated by Django 4.2.6 on 2023-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001CD51B934C0>', max_length=200),
        ),
    ]
