# Generated by Django 4.2.6 on 2023-11-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
