# Generated by Django 4.2.6 on 2023-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_password_reset_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_link_valid',
            field=models.BooleanField(default=False),
        ),
    ]
