# Generated by Django 4.2.6 on 2023-11-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0001_initial'),
        ('account', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vt_site.plan'),
        ),
    ]
