# Generated by Django 4.2.6 on 2023-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_coins_user_current_plan_user_pic_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
