# Generated by Django 4.2.6 on 2023-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_faq_cate_account_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_faq_cate',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
