# Generated by Django 4.2.6 on 2023-12-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_faq_cate_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
