# Generated by Django 4.2.6 on 2024-11-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_feedback_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics'),
        ),
    ]
