# Generated by Django 4.2.6 on 2024-11-23 03:33

import account.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics', validators=[functools.partial(account.models.validate_file_extension_and_mime, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
    ]
