# Generated by Django 5.0.6 on 2025-01-23 16:12

import account.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics', validators=[functools.partial(account.models.validate_file_extension_and_mime, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp'], 'allowed_mime_types': ['image/jpeg', 'image/png', 'image/gif', 'image/bmp']})]),
        ),
    ]
