# Generated by Django 4.2.6 on 2025-06-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_browser_user_ip_address_user_os_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_login_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
