# Generated by Django 4.2.6 on 2025-06-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_loginactivity_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loginactivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='last_login',
        ),
    ]
