# Generated by Django 4.2.6 on 2025-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_loginactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
