# Generated by Django 4.2.6 on 2025-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_loginactivity_browser_alter_loginactivity_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='browser',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='os',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
