# Generated by Django 4.2.6 on 2025-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_loginactivity_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
