# Generated by Django 4.2.6 on 2023-11-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Normal_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.plan')),
            ],
        ),
        migrations.CreateModel(
            name='NotAccepted_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.plan')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanPoint',
        ),
    ]
