# Generated by Django 4.2.6 on 2023-11-24 07:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0003_cookie_policy_privacy_policy_terms_of_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cookie_policy',
        ),
        migrations.DeleteModel(
            name='Privacy_policy',
        ),
        migrations.DeleteModel(
            name='Terms_of_use',
        ),
    ]
