# Generated by Django 4.2.6 on 2023-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0004_terms_pages_delete_cookie_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms_pages',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
