# Generated by Django 4.2.6 on 2023-11-24 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0005_terms_pages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms_pages',
            name='content',
            field=ckeditor.fields.RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field."),
        ),
    ]
