# Generated by Django 4.2.6 on 2023-11-24 13:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0006_alter_terms_pages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='background_color',
            field=colorfield.fields.ColorField(default='#313b44db', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='plan',
            name='color',
            field=colorfield.fields.ColorField(default='#09c4ff', image_field=None, max_length=25, samples=None),
        ),
    ]
