# Generated by Django 4.2.6 on 2023-11-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0007_plan_background_color_plan_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='media/teammates')),
                ('name', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=500)),
                ('insta_link', models.CharField(max_length=200)),
                ('linkedin_link', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='teammate_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.teammate')),
            ],
        ),
    ]
