# Generated by Django 4.2.6 on 2023-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0008_teammate_teammate_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='insta_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='linkedin_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
