# Generated by Django 4.2.6 on 2023-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0010_alter_teammate_email_id_alter_teammate_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/teammates'),
        ),
    ]
