# Generated by Django 4.2.6 on 2023-11-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0011_alter_teammate_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_desc', models.CharField(max_length=500)),
                ('copyright_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='site_details_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.site_details')),
            ],
        ),
    ]
