# Generated by Django 4.2.6 on 2023-11-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0012_site_details_site_details_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_title', models.CharField(max_length=100)),
                ('home_page_desc', models.CharField(max_length=200)),
                ('footer_desc', models.CharField(max_length=500)),
                ('copyright_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='site_details_links',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_site.site_detail'),
        ),
        migrations.DeleteModel(
            name='site_details',
        ),
    ]
