# Generated by Django 4.2.6 on 2023-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0013_site_detail_alter_site_details_links_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_detail',
            name='contact_mail',
            field=models.EmailField(default='abcd@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
