# Generated by Django 4.2.6 on 2023-12-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0015_faq_cate_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_detail',
            name='home_page_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
