# Generated by Django 4.2.6 on 2023-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0016_alter_site_detail_home_page_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_1',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_2',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_3',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_4',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_5',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
        migrations.AddField(
            model_name='site_detail',
            name='circle_animation_image_6',
            field=models.ImageField(null=True, upload_to='media/circle_animation'),
        ),
    ]
