# Generated by Django 4.2.6 on 2024-11-23 03:33

from django.db import migrations, models
import functools
import vt_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_site', '0017_site_detail_circle_animation_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_1',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_2',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_3',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_4',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_5',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='site_detail',
            name='circle_animation_image_6',
            field=models.ImageField(null=True, upload_to='media/circle_animation', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/teammates', validators=[functools.partial(vt_site.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
    ]
