# Generated by Django 4.2.6 on 2023-11-01 07:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('trending', 'trending'), ('none', 'none')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='tutorials_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutorial_chapter')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial_chapter',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutorial'),
        ),
    ]
