# Generated by Django 4.2.6 on 2023-11-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_tutorial_chapter_alter_tutorial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials_lesson',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
