# Generated by Django 4.2.6 on 2023-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_tutorials_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials_lesson',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
