# Generated by Django 4.2.6 on 2023-11-24 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_alter_tutorials_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial_category',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutorial_category',
            name='image',
            field=models.ImageField(null=True, upload_to='media/tutorial_category'),
        ),
        migrations.AlterField(
            model_name='tutorials_lesson',
            name='content',
            field=ckeditor.fields.RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field."),
        ),
    ]
