# Generated by Django 4.2.6 on 2024-11-23 03:33

from django.db import migrations, models
import functools
import tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_tutorial_category_desc_tutorial_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(null=True, upload_to='media/tutorial_imgs', validators=[functools.partial(tutorial.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
        migrations.AlterField(
            model_name='tutorial_category',
            name='image',
            field=models.ImageField(null=True, upload_to='media/tutorial_category', validators=[functools.partial(tutorial.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
    ]
