# Generated by Django 4.2.6 on 2024-09-29 09:45

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/course_imgs')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('sub_title', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Normal', 'Normal'), ('Pro', 'Pro')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('is_free_course', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('overview', ckeditor.fields.RichTextField(help_text="For consistency, use 'h2' for all headings and 'paragraph' formatting for text content within the Rich Text Field.")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_courses.course_category')),
            ],
        ),
        migrations.CreateModel(
            name='course_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='media/course_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_courses.course_chapter')),
            ],
        ),
        migrations.CreateModel(
            name='course_FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=5000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='video_courses.courses')),
            ],
        ),
        migrations.AddField(
            model_name='course_chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_courses.courses'),
        ),
    ]
