# Generated by Django 4.2.6 on 2024-09-29 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
