# Generated by Django 4.2.6 on 2024-10-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='purchased',
        ),
    ]
