# Generated by Django 4.2.6 on 2024-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0004_remove_courses_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lesson',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
