# Generated by Django 4.2.6 on 2024-11-23 03:27

from django.db import migrations, models
import functools
import video_courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0005_alter_course_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_lesson',
            old_name='video',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='course_lesson',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/course_videos', validators=[functools.partial(video_courses.models.validate_file_extension, *(), **{'allowed_extensions': ['.mp4', '.mov', '.avi', '.mkv', '.flv', '.wmv']})]),
        ),
    ]
