# Generated by Django 4.2.6 on 2024-11-23 03:33

from django.db import migrations, models
import functools
import video_courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0006_rename_video_course_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='media/course_imgs', validators=[functools.partial(video_courses.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
    ]
