# Generated by Django 5.0.6 on 2025-01-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0007_alter_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_images'),
        ),
    ]
