# Generated by Django 5.0.6 on 2025-01-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0008_course_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_category',
            name='image',
        ),
    ]
