# Generated by Django 5.0.6 on 2025-02-03 15:40

import functools
import video_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0009_remove_course_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lesson',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='course_videos', validators=[functools.partial(video_courses.models.validate_file_extension, *(), **{'allowed_extensions': ['.mp4', '.mov', '.avi', '.mkv', '.flv', '.wmv']})]),
        ),
    ]
