# Generated by Django 5.0.6 on 2025-02-08 16:38

import video_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0010_alter_course_lesson_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_category', validators=[video_courses.models.validate_file_extension]),
        ),
    ]
