# Generated by Django 5.0.6 on 2025-02-08 16:40

import functools
import video_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0011_course_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_category', validators=[functools.partial(video_courses.models.validate_file_extension, *(), **{'allowed_extensions': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']})]),
        ),
    ]
