# Generated by Django 4.2.6 on 2025-03-23 09:36

from django.db import migrations, models
import functools
import video_courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0012_alter_course_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/', validators=[functools.partial(video_courses.models.validate_file_extension, *(), **{'allowed_extensions': ['.mp4', '.mov', '.avi', '.mkv', '.flv', '.wmv']})]),
        ),
    ]
