# Generated by Django 4.2.6 on 2025-04-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0013_courses_intro_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='slug',
            new_name='course_slug',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='image',
            new_name='thumbline_image',
        ),
    ]
