# """
# Django settings for VulnTech_V3 project.

# Generated by 'django-admin startproject' using Django 4.0.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.0/ref/settings/
# """

# import os
# from pathlib import Path

# BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY = 'django-insecure-t-lsx-e%t6-9@b0*zj)*!w-&**f^28$_f80lrma!^+15!%hk^z'

# DEBUG = True

# ALLOWED_HOSTS = [
#     'https://vulntech.com',
#     'vulntech.com',
#     '127.0.0.1',
#     'localhost'
# ]

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [ BASE_DIR / "static" ]  # Optional, only if you have project-level static files
# STATIC_ROOT = BASE_DIR / "staticfiles"      # Required for collectstatic

# #CSRF_TRUSTED_ORIGINS = [
# #    'https://editor-coaches-environmental-curriculum.trycloudflare.com',
# #    'http://127.0.0.1:8080',
# #]

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'vt_site',
#     'tutorial',
#     'account',
#     'phonenumber_field',
#     'ckeditor',
#     'colorfield',
#     'video_courses',
#     'ide',
# ]

# CSRF_FAILURE_VIEW = 'account.views.custom_permission_denied_view'

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
#     'account.middleware.DeviceLimitMiddleware',                      
# ]

# AUTHENTICATION_BACKENDS = ['account.auth_backend.DeviceLimitBackend']

# ROOT_URLCONF = 'VulnTech_V3.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'vt_site/templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'VulnTech_V3.wsgi.application'

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'vulntech_db',
# #         'USER': 'db_admin',
# #         'PASSWORD': 'Admin@13579',
# #         'HOST': 'localhost',
# #         'PORT': '5432',
# #     }
# # }



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'vt_site',  'templates' ,'static'),  # Corrected path
# ]

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'account.User'

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# FILE_UPLOAD_PERMISSIONS = 0o644
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # EMAIL_HOST = "smtp.hostinger.com"
# EMAIL_HOST = "mail.vulnix.org"
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "verification@vulnix.org"
# EMAIL_HOST_PASSWORD = "VerificaTion@808"
# DEFAULT_FROM_EMAIL = "verification@vulnix.org"
# CSP_DEFAULT_SRC = ("'self'",)
# # RAZORPAY_KEY_ID = 'rzp_test_jvp5NH8bLOblMq'
# # RAZORPAY_KEY_SECRET = 'O8MNBRngtMTJSBu2LKqACNHG'
# RAZORPAY_KEY_ID = 'rzp_live_yScktHn3SUYxnY'
# RAZORPAY_KEY_SECRET = '01ZKDo9VT7s2FbEg1H3B1nMY'
# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

"""
Django settings for VulnTech_V3 project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t-lsx-e%t6-9@b0*zj)*!w-&**f^28$_f80lrma!^+15!%hk^z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'account.apps.AccountConfig',  # ✅ Keep only this
    'vt_site',
    'tutorial',
    'phonenumber_field',
    'ckeditor',
    'colorfield',
    'video_courses',
    'ide',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VulnTech_V3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'vt_site/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VulnTech_V3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'vt_site/templates/static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'account.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_AGE = 600 

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.hostinger.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# EMAIL_HOST_USER = "rcky930@gmail.com"
EMAIL_HOST_USER = "verification@vulnix.org"
# EMAIL_HOST_PASSWORD = "hgsn ywnb jalf qgvb"
EMAIL_HOST_PASSWORD = "VerificaTion@808"
DEFAULT_FROM_EMAIL = 'support@vulntech.com'

# razorpay
RAZORPAY_KEY_ID = 'rzp_test_jvp5NH8bLOblMq'
RAZORPAY_KEY_SECRET = 'O8MNBRngtMTJSBu2LKqACNHG'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

CSRF_FAILURE_VIEW = 'account.views.custom_permission_denied_view'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',         
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',       
    'django.contrib.messages.middleware.MessageMiddleware',          
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'account.middleware.DeviceLimitMiddleware',                      
]
AUTHENTICATION_BACKENDS = ['account.auth_backend.DeviceLimitBackend']

